- name: Test preparation
  hosts: migrator
  tasks:
    - name: clean pre workloads
      ansible.builtin.include_tasks: clean_pre_src_workload.yml
      with_items: objs
      # This loop means that we will create 8 resources when cleaning the environment
      loop: "{{ query('sequence', 'start=1 end={{ amount_resources }}') }}"
      loop_control:
        loop_var: loop_index

    - name: clean workloads
      ansible.builtin.include_tasks: clean_src_workload.yml
      when: False
      with_items: objs
      loop: "{{ query('sequence', 'start=1 end={{ amount_resources }}') }}"
      loop_control:
        loop_var: loop_index
