# - name: Remove workload test data
#   ansible.builtin.file:
#     path: "{{ os_migrate_data_dir }}/{{ item }}"
#     state: absent
#   loop:
#     - osm_bench_server.log
#     - osm_bench_server.state
#     - workloads.yml

- name: Detach src volumes if still attached
  openstack.cloud.server_volume:
    server: "{{ item.server }}"
    volume: "{{ item.volume }}"
    state: absent
    auth: "{{ os_migrate_src_auth }}"
    validate_certs: "{{ os_migrate_src_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_src_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_src_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_src_client_key|default(omit) }}"
  loop:
    - server: os_migrate_conv
      volume: os-migrate-osm_bench_server
    - server: os_migrate_conv
      volume: osm_bench_volume
    - server: osm_bench_server
      volume: osm_bench_volume
  # The module will fail if server or volume don't exist.
  failed_when: false
  ignore_errors: True

- name: Remove osm_bench_server
  openstack.cloud.server:
    name: osm_bench_server
    state: absent
    delete_fip: yes
    auth: "{{ item.auth }}"
    validate_certs: "{{ item.validate_certs }}"
    ca_cert: "{{ item.ca_cert }}"
    client_cert: "{{ item.client_cert }}"
    client_key: "{{ item.client_key }}"
    wait: yes
  loop:
    - auth: "{{ os_migrate_src_auth }}"
      validate_certs: "{{ os_migrate_src_validate_certs|default(omit) }}"
      ca_cert: "{{ os_migrate_src_ca_cert|default(omit) }}"
      client_cert: "{{ os_migrate_src_client_cert|default(omit) }}"
      client_key: "{{ os_migrate_src_client_key|default(omit) }}"
  ignore_errors: True

- name: Remove osm_bench_server boot volume
  openstack.cloud.volume:
    display_name: os-migrate-osm_bench_server
    state: absent
    auth: "{{ item.auth }}"
    validate_certs: "{{ item.validate_certs }}"
    ca_cert: "{{ item.ca_cert }}"
    client_cert: "{{ item.client_cert }}"
    client_key: "{{ item.client_key }}"
  loop:
    - auth: "{{ os_migrate_src_auth }}"
      validate_certs: "{{ os_migrate_src_validate_certs|default(omit) }}"
      ca_cert: "{{ os_migrate_src_ca_cert|default(omit) }}"
      client_cert: "{{ os_migrate_src_client_cert|default(omit) }}"
      client_key: "{{ os_migrate_src_client_key|default(omit) }}"
  ignore_errors: True

- name: Remove osm_bench_volume
  openstack.cloud.volume:
    display_name: osm_bench_volume
    state: absent
    auth: "{{ item.auth }}"
    validate_certs: "{{ item.validate_certs }}"
    ca_cert: "{{ item.ca_cert }}"
    client_cert: "{{ item.client_cert }}"
    client_key: "{{ item.client_key }}"
  loop:
    - auth: "{{ os_migrate_src_auth }}"
      validate_certs: "{{ os_migrate_src_validate_certs|default(omit) }}"
      ca_cert: "{{ os_migrate_src_ca_cert|default(omit) }}"
      client_cert: "{{ os_migrate_src_client_cert|default(omit) }}"
      client_key: "{{ os_migrate_src_client_key|default(omit) }}"
  ignore_errors: True
