- name: Test preparation
  hosts: migrator
  tasks:
    - name: seed pre workloads
      ansible.builtin.include_tasks: seed_pre_workload.yml
      with_items: objs
      loop: "{{ query('sequence', 'start=1 end=1') }}"
      loop_control:
        loop_var: loop_index
      vars:
        experiment: "1"

    - name: seed workloads
      ansible.builtin.include_tasks: seed_workload.yml
      when: False
      with_items: objs
      loop: "{{ query('sequence', 'start=1 end=1') }}"
      loop_control:
        loop_var: loop_index
